[2024-10-06T18:14:52.986+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T18:14:53.048+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-07T01:13:56+07:00 [queued]>
[2024-10-06T18:14:53.086+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-07T01:13:56+07:00 [queued]>
[2024-10-06T18:14:53.088+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T18:14:53.131+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): choose_source> on 2024-10-06 18:13:56+00:00
[2024-10-06T18:14:53.162+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T18:14:53.167+0000] {standard_task_runner.py:72} INFO - Started process 254 to run task
[2024-10-06T18:14:53.163+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'choose_source', 'manual__2024-10-07T01:13:56+07:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpfbbidegx']
[2024-10-06T18:14:53.170+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask choose_source
[2024-10-06T18:14:53.383+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.choose_source manual__2024-10-07T01:13:56+07:00 [running]> on host 17f17543b6e1
[2024-10-06T18:14:53.755+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='choose_source' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T18:13:56+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-07T01:13:56+07:00'
[2024-10-06T18:14:53.764+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T18:14:53.818+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-06T18:14:53.820+0000] {logging_mixin.py:190} INFO - Selected source type: json
[2024-10-06T18:14:53.821+0000] {python.py:240} INFO - Done. Returned value was: extract_json
[2024-10-06T18:14:53.822+0000] {branch.py:38} INFO - Branch into extract_json
[2024-10-06T18:14:53.823+0000] {skipmixin.py:230} INFO - Following branch ('extract_json',)
[2024-10-06T18:14:53.863+0000] {skipmixin.py:278} INFO - Skipping tasks [('extract_csv', -1)]
[2024-10-06T18:14:53.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T18:14:53.996+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=choose_source, run_id=manual__2024-10-07T01:13:56+07:00, execution_date=20241006T181356, start_date=20241006T181453, end_date=20241006T181453
[2024-10-06T18:14:54.104+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T18:14:54.276+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T18:14:54.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
