[2024-10-06T16:35:37.532+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T16:35:37.756+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:29:26+07:00 [queued]>
[2024-10-06T16:35:37.870+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:29:26+07:00 [queued]>
[2024-10-06T16:35:37.876+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-06T16:35:38.009+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): choose_source> on 2024-10-06 16:29:26+00:00
[2024-10-06T16:35:38.093+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T16:35:38.210+0000] {standard_task_runner.py:72} INFO - Started process 197 to run task
[2024-10-06T16:35:38.200+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'choose_source', 'manual__2024-10-06T23:29:26+07:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpc79ze8td']
[2024-10-06T16:35:38.265+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask choose_source
[2024-10-06T16:35:38.822+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.choose_source manual__2024-10-06T23:29:26+07:00 [running]> on host d0efb872fab5
[2024-10-06T16:35:44.200+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='choose_source' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T16:29:26+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T23:29:26+07:00'
[2024-10-06T16:35:44.216+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T16:35:44.350+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-06T16:35:44.356+0000] {logging_mixin.py:190} INFO - Selected source type: csv
[2024-10-06T16:35:44.357+0000] {python.py:240} INFO - Done. Returned value was: extract_csv
[2024-10-06T16:35:44.358+0000] {branch.py:38} INFO - Branch into extract_csv
[2024-10-06T16:35:44.359+0000] {skipmixin.py:230} INFO - Following branch ('extract_csv',)
[2024-10-06T16:35:44.412+0000] {skipmixin.py:278} INFO - Skipping tasks [('extract_json', -1)]
[2024-10-06T16:35:44.617+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T16:35:44.622+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=choose_source, run_id=manual__2024-10-06T23:29:26+07:00, execution_date=20241006T162926, start_date=20241006T163537, end_date=20241006T163544
[2024-10-06T16:35:44.875+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T16:35:45.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
