[2024-10-06T13:56:15.370+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T13:56:15.446+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T20:53:02+07:00 [queued]>
[2024-10-06T13:56:15.503+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.choose_source manual__2024-10-06T20:53:02+07:00 [queued]>
[2024-10-06T13:56:15.509+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T13:56:15.566+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): choose_source> on 2024-10-06 13:53:02+00:00
[2024-10-06T13:56:15.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T13:56:15.613+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2024-10-06T13:56:15.614+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'choose_source', 'manual__2024-10-06T20:53:02+07:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp0g_grtka']
[2024-10-06T13:56:15.627+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask choose_source
[2024-10-06T13:56:16.968+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.choose_source manual__2024-10-06T20:53:02+07:00 [running]> on host 088e16a81275
[2024-10-06T13:56:17.222+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='choose_source' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T13:53:02+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T20:53:02+07:00'
[2024-10-06T13:56:17.230+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T13:56:17.331+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-10-06T13:56:17.332+0000] {logging_mixin.py:190} INFO - Selected source type: csv
[2024-10-06T13:56:17.333+0000] {python.py:240} INFO - Done. Returned value was: extract_csv
[2024-10-06T13:56:17.334+0000] {branch.py:38} INFO - Branch into extract_csv
[2024-10-06T13:56:17.335+0000] {skipmixin.py:230} INFO - Following branch ('extract_csv',)
[2024-10-06T13:56:17.381+0000] {skipmixin.py:278} INFO - Skipping tasks [('extract_json', -1)]
[2024-10-06T13:56:17.510+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T13:56:17.512+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=choose_source, run_id=manual__2024-10-06T20:53:02+07:00, execution_date=20241006T135302, start_date=20241006T135615, end_date=20241006T135617
[2024-10-06T13:56:17.607+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T13:56:18.265+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T13:56:18.276+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
